# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddr', models.GenericIPAddressField(default='127.0.0.1')),
                ('timeVisited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
